use_frameworks!

platform :ios, '8.0'

target 'DataBaseCore_Example' do
  pod 'DataBaseCore', :path => '../'

  target 'DataBaseCore_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
